blog academy/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", home, name="home"),
    path("post/<int:pk>/", post, name="post"),
    path("create_post/", create_post, name="create_post"),
    path("edit_post/<int:pk>", edit_post, name="edit_post"),
    path('delete_post/<int:pk>', delete_post, name='delete_post'),
    path('comment_delete/<int:pk>', comment_delete, name='comment_delete'),
    path('comment_edit/<int:pk>', comment_edit, name='comment_edit'),
    path('post_like/<int:pk>', post_like, name='post_like'),
    path('post_dislike/<int:pk>', post_dislike, name='post_dislike'),
    path('comment_like/<int:pk>', comment_like, name='comment_like'),
    path('comment_dislike/<int:pk>', comment_dislike, name='comment_dislike'),
    path('reply/<int:pk>/', reply, name='reply'),
    path('read_comment/<int:pk>', read_comment, name='read_comment'),
] 

blog academy/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include(("app.urls", "app"), namespace="app")),
    path("users/", include(("users.urls", "users"), namespace="users")),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog academy/users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('register/', register, name='register'),
]

blog academy/app/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    image = models.ImageField(blank=True, default='default.png')
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=1)
    likes = models.ManyToManyField('auth.User', related_name='likes')
    dislikes = models.ManyToManyField('auth.User', related_name='dislikes')
    views = models.ManyToManyField('auth.User', related_name='views')

    def __str__(self):
        return self.title   

    def snippet(self):
        return self.body[:30] + '...'
    
    def title_snippet(self):
        return self.title[:20] + '...' 


class Comment(models.Model):
    body = models.TextField()
    date_created = models.DateField(auto_now_add=True)
    date_edited = models.DateField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    is_edited = models.BooleanField(default=False)
    likes = models.ManyToManyField('auth.User', related_name='comment_likes')
    dislikes = models.ManyToManyField('auth.User', related_name='comment_dislikes')
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='reply'
    )

    def __str__(self):
        return self.body

blog academy/app/templates/base_layout.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>
    <script defer src="{% static 'script.js' %}"></script>
  </head>
  <body>
    <a class="to-start" href="#header">
      <ion-icon name="arrow-up"></ion-icon>
    </a>
    <header id="header">
      <nav class="navbar">
        <div class="navbar-start">
          <a class="navbar-logo" href="{% url 'app:home' %}">
            <img
              src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg"
              alt=""
            />
          </a>
        </div>
        <div class="navbar-menu">
          <div class="navbar-item">
            <form action="" method="get">
              <input type="search" name="q" placeholder="Поиск по сайту">
            </form>
          </div>
          {% if user.is_authenticated %}
          <div class="navbar-item">
            <a class="button primary" href="{% url 'app:create_post' %}">
              Создать пост
            </a>
          </div>
          {% endif %}
          <div class="navbar-item">
            {% if not user.is_authenticated %}
            <a class="button primary" href="{% url 'users:login' %}"> Войти </a>
            {% else %}
            <a class="button danger" href="{% url 'users:logout' %}"> Выйти </a>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

blog academy/app/templates/comment_delete.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <div class="title">Подтвердите удаление комментария</div>

    <div class="buttons">
      <button class="button primary">
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </button>
      <a class="button danger" href="{% url 'app:post' comment.post.pk %}">
        <ion-icon name="close-circle-outline"></ion-icon>
      </a>
    </div>
  </form>
</div>
{% endblock %}

blog academy/app/templates/delete_post.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <div class="title">Подтвердите удаление поста</div>

    <div class="buttons">
      <button class="button primary">
        <ion-icon name="checkmark-circle-outline"></ion-icon>
      </button>
      <a class="button danger" href="{% url 'app:post' pk %}">
        <ion-icon name="close-circle-outline"></ion-icon>
      </a>
    </div>
  </form>
</div>
{% endblock %}

blog academy/app/templates/form.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% for field in form %}
      <div class="field">
        {{field}}
      </div>
      {% endfor %}
      <button>Ok</button>
    </form>
  </div>
{% endblock %}

blog academy/app/templates/home.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="home-container">
    {% if posts %}
      {% for post in posts %}
      <a class="post" href="{% url 'app:post' post.pk %}">
        <div>
          <div class="title">{{post.title_snippet}}</div>
          <div class="author">Опубликовано: {{post.author}}</div>
        </div>
        <div>
          <div class="text">{{post.snippet}}</div>
          <div class="date">{{post.created_at}}</div>
        </div>
        <div class="post-statistics">
          <div class="stat">
            <ion-icon name="thumbs-up"></ion-icon>
            {{post.likes.count}}
          </div>
          <div class="stat">
            <ion-icon name="thumbs-down"></ion-icon>
            {{post.dislikes.count}}
          </div>
          <div class="stat">
            <ion-icon name="chatbubble"></ion-icon>
            {{post.comment_set.count}}
          </div>
          <div class="stat">
            <ion-icon name="eye"></ion-icon>
            {{post.views.count}}
          </div>
        </div>
      </a>
      {% endfor %}
    {% else %}
      <div class="title">Посты не найдены</div>
    </div>
    {% endif %}
  </div>
  {% if posts.count < all_posts_count and all_posts_count > 0 %}
  <div class="show-more">
    <a class="button primary" href="{% url 'app:home' %}?quantity={{posts.count|add:3}}">
      Показать больше
    </a>
  </div>
  {% endif %}
{% endblock %}

blog academy/app/templates/post.html
{% extends 'base_layout.html' %}


{% block content %}

<div class="post-container">
  <div class="header">
    <div>
      <div class="title">{{post.title}}</div>
      <div class="info">Добавлено: {{post.created_at|date:'d.m.Y'}}</div>
    </div>
    {% if post.author == user or user.is_staff %}
    <div class="buttons">
      <a href="{% url 'app:edit_post' post.pk %}" class="button primary">
        <ion-icon name="create-outline"></ion-icon>
      </a>
      <a href="{% url 'app:delete_post' post.pk %}" class="button danger">
        <ion-icon name="trash-outline"></ion-icon>
      </a>
    </div>
    {% endif %}
  </div>

  <div class="image">
    <img src="{{ post.image.url }}" alt="" />
  </div>
  <div class="post-body">{{post.body}}</div>
  <hr />
  <div class="post-buttons">
    <a
      href="{% url 'app:post_like' post.pk %}"
      class="post-button {% if user in post.likes.all %} primary {% endif %}"
    >
      <ion-icon name="thumbs-up-outline"></ion-icon>
      {{post.likes.count}}
    </a>
    <a
      href="{% url 'app:post_dislike' post.pk %}"
      class="post-button {% if user in post.dislikes.all %} danger {% endif %}"
    >
      <ion-icon name="thumbs-down-outline"></ion-icon>
      {{post.dislikes.count}}
    </a>
  </div>

  <form class="comments" method="post">
    {% csrf_token %} {% for field in form %}
    <input
      type="text"
      class="input"
      name="{{field.name}}"
      placeholder="Введите комментарий"
    />
    {% endfor %}

    <div class="title">Комментариев: {{ post.comment_set.all.count }}</div>
  </form>

  <div class="comments-list">
    {% for comment in post_comments %}
    <div class="comment">
      {% if comment.parent %}
      <div class="is-reply">
        <ion-icon name="arrow-undo"></ion-icon>
        <div class="text">
          В ответ на "{{comment.parent.body|slice:":10" }}..."
        </div>
      </div>
      {% endif %} 
      {% if user == comment.author %}
      <div class="comment-buttons">
        <a
          class="comment-button primary"
          href="{% url 'app:comment_edit' comment.pk %}"
        >
          <ion-icon name="create-outline"></ion-icon>
        </a>
        <a
          class="comment-button danger"
          href="{% url 'app:comment_delete' comment.pk %}"
        >
          <ion-icon name="trash-outline"></ion-icon>
        </a>
      </div>
      {% endif %}
      <div class="comment-head">
        <div class="avatar">
          <img
            src="https://static-00.iconduck.com/assets.00/avatar-default-icon-2048x2048-h6w375ur.png"
            alt=""
          />
        </div>
        <div class="user-data">
          <div class="username">{{comment.author}}</div>
          <div class="date">{{comment.date_created}}</div>
        </div>
      </div>
      <div class="comment-body">
        {% if comment.body|length <= 10 %} {{comment.body}} {% else %}
        {{comment.body|slice:":10"}}...
        <a сlass="read-more" href="{% url 'app:read_comment' comment.pk %}">
          Читать далее
        </a>
        {% endif %}
      </div>
      <div class="comment-footer">
        <div class="buttons">
          <a
            href="{% url 'app:comment_like' comment.pk %}"
            class="btn {% if user in comment.likes.all %} primary {% endif %}"
          >
            <ion-icon name="thumbs-up-outline"></ion-icon>
            {{comment.likes.count}}
          </a>
          <a
            href="{% url 'app:comment_dislike' comment.pk %}"
            class="btn {% if user in comment.dislikes.all %} danger {% endif %}"
          >
            <ion-icon name="thumbs-down-outline"></ion-icon>
            {{comment.likes.count}}
          </a>
        </div>
        <a href="{% url 'app:reply' comment.pk %}" class="reply"> Reply </a>
      </div>
      <div class="edited">
        {% if comment.is_edited %} Отредактировано {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  {% if post_comments.has_other_pages %}
  <div class="pagination-buttons">
    <div class="previous">
      {% if post_comments.has_previous %}
      <a href="{% url 'app:post' post.pk %}?page=1" class="button">
        В начало
      </a>
      <a href="{% url 'app:post' post.pk %}?page={{post_comments.previous_page_number}}" class="button">
        Назад
        </a>
      {% endif %}
    </div>
    <div class="current-page">
      {{post_comments.number}}
    </div>
   <div class="next">
    {% if post_comments.has_next %}
    <a href="{% url 'app:post' post.pk %}?page={{post_comments.next_page_number}}" class="button">
      Далее
      </a>
      <a href="{% url 'app:post' post.pk %}?page={{post_comments.paginator.num_pages}}" class="button">
        В конец
      </a>
    {% endif %}
   </div>
  </div>
  {% endif %}
</div>
{% endblock %}

blog academy/app/templates/post_form.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="container">
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% for field in form %}
      <div class="field">
        {{field}}
      </div>
      {% endfor %}
      <button>Ok</button>
    </form>
  </div>
{% endblock %}

blog academy/app/templates/read_comment.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="parent-block">
  <div class="block">
    <a href="{% url 'app:post' comment.post.pk %}" class="button">Назад к посту</a>
    <div class="title">Пост: {{comment.post.title}}</div>
    <div class="comment-text">Полный комментарий: {{comment.body}}</div>
    <div class="date-added">Дата добавления: {{comment.date_created|date:'d.m.Y'}}</div>
    <div class="comment-author">Автор: {{comment.author}}</div>

    <div class="buttons">
      <a href="{% url 'app:home' %}" class="button">На главную</a>
      <a href="{%  url 'app:reply' comment.pk %}" class="button">
        <ion-icon name="arrow-undo"></ion-icon>
        <span>Ответить</span>
      </a>
    </div>
  </div>
</div>
{% endblock %}